import type { Metadata } from "next";
import "./globals.css";
import { barlow } from "./ui/fonts";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} text-white flex flex-col`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
